config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :users
  resources :subcategories
  resources :uoms
  resources :suppliers
  resources :categories
  resources :products
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: %i[ show edit update destroy ]

  # GET /subcategories or /subcategories.json
  def index
    @subcategories = Subcategory.all
  end

  # GET /subcategories/1 or /subcategories/1.json
  def show
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit
  end

  # POST /subcategories or /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to subcategory_url(@subcategory), notice: "Subcategory was successfully created." }
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1 or /subcategories/1.json
  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to subcategory_url(@subcategory), notice: "Subcategory was successfully updated." }
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1 or /subcategories/1.json
  def destroy
    @subcategory.destroy!

    respond_to do |format|
      format.html { redirect_to subcategories_url, notice: "Subcategory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subcategory_params
      params.require(:subcategory).permit(:category_id, :sub_category_name, :description_string)
    end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<%= form_with(model: subcategory) do |form| %>
  <% if subcategory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
        <% subcategory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.label :sub_category_name, style: "display: block" %>
    <%= form.text_field :sub_category_name %>
  </div>

  <div>
    <%= form.label :description_string, style: "display: block" %>
    <%= form.text_field :description_string %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subcategories/_subcategory.html.erb
<div id="<%= dom_id subcategory %>">
  <p>
    <strong>Category:</strong>
    <%= subcategory.category_id %>
  </p>

  <p>
    <strong>Sub category name:</strong>
    <%= subcategory.sub_category_name %>
  </p>

  <p>
    <strong>Description string:</strong>
    <%= subcategory.description_string %>
  </p>

</div>

app/views/subcategories/edit.html.erb
<h1>Editing subcategory</h1>

<%= render "form", subcategory: @subcategory %>

<br>

<div>
  <%= link_to "Show this subcategory", @subcategory %> |
  <%= link_to "Back to subcategories", subcategories_path %>
</div>

app/views/subcategories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Subcategories</h1>

<div id="subcategories">
  <% @subcategories.each do |subcategory| %>
    <%= render subcategory %>
    <p>
      <%= link_to "Show this subcategory", subcategory %>
    </p>
  <% end %>
</div>

<%= link_to "New subcategory", new_subcategory_path %>

app/views/subcategories/new.html.erb
<h1>New subcategory</h1>

<%= render "form", subcategory: @subcategory %>

<br>

<div>
  <%= link_to "Back to subcategories", subcategories_path %>
</div>

app/views/subcategories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subcategory %>

<div>
  <%= link_to "Edit this subcategory", edit_subcategory_path(@subcategory) %> |
  <%= link_to "Back to subcategories", subcategories_path %>

  <%= button_to "Destroy this subcategory", @subcategory, method: :delete %>
</div>