config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :users
  resources :subcategories
  resources :uoms
  resources :suppliers
  resources :categories
  resources :products
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/uom.rb
class Uom < ApplicationRecord
end

app/controllers/uoms_controller.rb
class UomsController < ApplicationController
  before_action :set_uom, only: %i[ show edit update destroy ]

  # GET /uoms or /uoms.json
  def index
    @uoms = Uom.all
  end

  # GET /uoms/1 or /uoms/1.json
  def show
  end

  # GET /uoms/new
  def new
    @uom = Uom.new
  end

  # GET /uoms/1/edit
  def edit
  end

  # POST /uoms or /uoms.json
  def create
    @uom = Uom.new(uom_params)

    respond_to do |format|
      if @uom.save
        format.html { redirect_to uom_url(@uom), notice: "Uom was successfully created." }
        format.json { render :show, status: :created, location: @uom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @uom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uoms/1 or /uoms/1.json
  def update
    respond_to do |format|
      if @uom.update(uom_params)
        format.html { redirect_to uom_url(@uom), notice: "Uom was successfully updated." }
        format.json { render :show, status: :ok, location: @uom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @uom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uoms/1 or /uoms/1.json
  def destroy
    @uom.destroy!

    respond_to do |format|
      format.html { redirect_to uoms_url, notice: "Uom was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uom
      @uom = Uom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def uom_params
      params.require(:uom).permit(:name, :description)
    end
end

app/helpers/uoms_helper.rb
module UomsHelper
end

app/views/uoms/_form.html.erb
<%= form_with(model: uom) do |form| %>
  <% if uom.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(uom.errors.count, "error") %> prohibited this uom from being saved:</h2>

      <ul>
        <% uom.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/uoms/_uom.html.erb
<div id="<%= dom_id uom %>">
  <p>
    <strong>Name:</strong>
    <%= uom.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= uom.description %>
  </p>

</div>

app/views/uoms/edit.html.erb
<h1>Editing uom</h1>

<%= render "form", uom: @uom %>

<br>

<div>
  <%= link_to "Show this uom", @uom %> |
  <%= link_to "Back to uoms", uoms_path %>
</div>

app/views/uoms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Uoms</h1>

<div id="uoms">
  <% @uoms.each do |uom| %>
    <%= render uom %>
    <p>
      <%= link_to "Show this uom", uom %>
    </p>
  <% end %>
</div>

<%= link_to "New uom", new_uom_path %>

app/views/uoms/new.html.erb
<h1>New uom</h1>

<%= render "form", uom: @uom %>

<br>

<div>
  <%= link_to "Back to uoms", uoms_path %>
</div>

app/views/uoms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @uom %>

<div>
  <%= link_to "Edit this uom", edit_uom_path(@uom) %> |
  <%= link_to "Back to uoms", uoms_path %>

  <%= button_to "Destroy this uom", @uom, method: :delete %>
</div>